DROP TABLE PINVOICEL;

CREATE TABLE PINVOICEL(
PINV_REF            VARCHAR(12)     NOT NULL,
PINV_LINE		    NUMBER          NOT NULL,
PO_REF              VARCHAR(5)      NOT NULL,
PO_LINE		        NUMBER          NOT NULL,
LINE_AMOUNT	        NUMBER          NOT NULL,
STATUS              VARCHAR(10)     NOT NULL,    
HOLD_REASON         VARCHAR(50),            
LINE_DESCRIPTION    VARCHAR(50),
PAY_REF             VARCHAR(6),
CONSTRAINT PK_PINVOICEL
    PRIMARY KEY (PINV_REF, PINV_LINE),
CONSTRAINT FK_PINVL_PINV
    FOREIGN KEY (PINV_REF) 
    REFERENCES PINVOICE(PINV_REF),
CONSTRAINT FK_PINVL_POL
    FOREIGN KEY (PO_REF,PO_LINE) 
    REFERENCES PORDERL(PO_REF,PO_LINE)

);
