DROP TABLE PORDERL;

CREATE TABLE PORDERL(
PO_REF          VARCHAR(5)      NOT NULL,
PO_LINE		    NUMBER          NOT NULL,
LINE_AMOUNT	    NUMBER          NOT NULL,
CONSTRAINT PK_PORDERL
    PRIMARY KEY (PO_REF,PO_LINE),
CONSTRAINT FK_POL_PO
    FOREIGN KEY (PO_REF) 
    REFERENCES PORDER(PO_REF)
);


