--Purchase invoice migration
CREATE OR REPLACE PROCEDURE JNABCM.MIGRATE_PINVOICE IS
BEGIN
INSERT INTO PINVOICE
(INVPO_REF,
INV_DATE,
SUPPLIER_REF,
INV_AMOUNT,
DESCRIPTION
)
SELECT
INVPO_REF,
INV_DATE,
SUPPLIER_REF,
SUM(AMOUNT),
MAX(DESCRIPTION)
FROM
(
SELECT 
INVOICE_REFERENCE AS INVPO_REF,
CASE 
    WHEN LENGTH(TRIM(TRANSLATE(SUBSTR(INVOICE_DATE,4,2), 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ' ')))IS NULL THEN
        TO_DATE(INVOICE_DATE,'DD-Mon-YY')
    ELSE
        TO_DATE(INVOICE_DATE,'DD/MM/YYYY')
END INV_DATE,
GET_SUPPLIER(SUPPLIER_NAME) AS SUPPLIER_REF,
CASE 
    WHEN CAST(REPLACE(INVOICE_AMOUNT,',') AS NUMBER DEFAULT 0 ON CONVERSION ERROR)<>0 THEN 
        TO_NUMBER(REPLACE(INVOICE_AMOUNT,','))
    WHEN CAST(REPLACE(ORDER_LINE_AMOUNT,',') AS NUMBER DEFAULT 0 ON CONVERSION ERROR)<>0 THEN 
        TO_NUMBER(REPLACE(ORDER_LINE_AMOUNT,','))
    WHEN CAST(REPLACE(ORDER_TOTAL_AMOUNT,',') AS NUMBER DEFAULT 0 ON CONVERSION ERROR)<>0 THEN 
        TO_NUMBER(REPLACE(ORDER_TOTAL_AMOUNT,','))  
    ELSE 
        0
END AS AMOUNT,
INVOICE_DESCRIPTION AS DESCRIPTION
FROM XXBCM_ORDER_MGT
WHERE INVOICE_REFERENCE IS NOT NULL
ORDER BY INVOICE_REFERENCE)
GROUP BY INVPO_REF,INV_DATE,SUPPLIER_REF
ORDER BY INVPO_REF;
END;