--Purchase order line migration
CREATE OR REPLACE PROCEDURE JNABCM.MIGRATE_PORDERL IS
BEGIN
INSERT INTO PORDERL
SELECT 
SUBSTR(ORDER_REF,1,5) AS ORDER_REF,
TO_NUMBER(SUBSTR(ORDER_REF,7,8)) AS ORDER_LINE,
SUM(CASE 
    WHEN CAST(REPLACE(INVOICE_AMOUNT,',') AS NUMBER DEFAULT 0 ON CONVERSION ERROR)<>0 THEN 
        TO_NUMBER(REPLACE(INVOICE_AMOUNT,','))
    WHEN CAST(REPLACE(ORDER_LINE_AMOUNT,',') AS NUMBER DEFAULT 0 ON CONVERSION ERROR)<>0 THEN 
        TO_NUMBER(REPLACE(ORDER_LINE_AMOUNT,','))
    WHEN CAST(REPLACE(ORDER_TOTAL_AMOUNT,',') AS NUMBER DEFAULT 0 ON CONVERSION ERROR)<>0 THEN 
        TO_NUMBER(REPLACE(ORDER_TOTAL_AMOUNT,','))  
    ELSE 
        0
END) AS AMOUNT 
FROM XXBCM_ORDER_MGT WHERE LENGTH(ORDER_REF)>5
GROUP BY ORDER_REF
ORDER by ORDER_REF,ORDER_LINE;  
END;